In Puppet 3.7, `contain heat` from within quickstack::heat is going to resolve to `contain ::quickstack::heat` instead of `contain ::heat`, causing a dep cycle:
Error: Could not apply complete catalog: Found 2 dependency cycles:
(Class[Quickstack::Heat] => Class[Quickstack::Heat])
(Class[Quickstack::Heat] => Class[Quickstack::Heat])

However, in Puppet 3.6 the current code seems to behave correctly, and
furthermore it cannot cope with the fixed Puppet 3.7 syntax.

Add a conditional on this one spot to allow running both on Puppet 3.6
and 3.7. After we drop support for Puppet 3.6 syntax, we should remove
the conditional and use the Puppet 3.7 syntax `contain ::someclass`
everywhere.