Use absolute namespace with 'contain'
"contain heat" from within quickstack::heat is going to resolve to
"contain ::quickstack::heat" instead of "contain ::heat", causing
a dep cycle:

Error: Could not apply complete catalog: Found 2 dependency cycles:
(Class[Quickstack::Heat] => Class[Quickstack::Heat])
(Class[Quickstack::Heat] => Class[Quickstack::Heat])

This commit makes use of absolute namespacing with 'contain' to avoid
such naming collisions.